### ISSUE TITLE
pipe.enable_sequential_cpu_offload()

### ISSUE THREAD

**Issue by al-swaiti** [sayakpaul/diffusers-torchao#36]
how to enable pipe.enable_sequential_cpu_offload() to run benchmark_image.py  on lower gpu <16 , also could we save quantized model to load it directly to inference

**Comment by a-r-r-o-w** [comment]
The README already [links](https://github.com/sayakpaul/diffusers-torchao/blob/main/inference/serialization_and_loading.md) to a guide on how to serialize a quantized model and load it directly for inference.

There are many examples available online, or have been shared by Sayak, for running Flux in under 16 GB. In fact, you could do it in under 5 GB at the cost of slow inference for even lower vram GPUs.

**Comment by al-swaiti** [comment]
i know that , but is there way to apply this to this code  benchmark_image.py

**Comment by a-r-r-o-w** [comment]
There are no plans to extend the scripts to have any other functionality as our benchmarks are to demonstrate memory/time savings on a full pipeline run without any additional optimizations - that is, we only want to test the benefits of torchao without other things. If you'd like to have other optimizations for testing, feel free to maintain a fork

**Comment by al-swaiti** [comment]
okay thanks
