### ISSUE TITLE
Inference is fast but saving is slow.

### ISSUE THREAD

**Issue by Leommm-byte** [sayakpaul/diffusers-torchao#38]
I noticed something when I tried to use torch.compile (similar to the way it's used here) on RunPod. I am using it on an A100 80gb.

What I noticed is that the inference time is really fast, but the time to actually decode and save is way slow. I did some digging into it and realized that it is actually the time to move the tensors from GPU to CPU that took the time. The funny thing is, during the first run (which is when the compilation happens), because it takes time, the saving of the image is really fast but after that, inference is fast but saving is slow. It is more like the saving tries to account for the speed gained while inference. 

I've been battling with this all day and I'll really appreciate if anyone can help with this. 

Here's the code I ran (yeah I didn't quantize)
```
import torch
from diffusers import FluxPipeline
from PIL import Image
import numpy as np
import time
from torchvision.transforms import ToPILImage

torch.set_float32_matmul_precision("high")

model = "dev"

pipe = FluxPipeline.from_pretrained(f"black-forest-labs/FLUX.1-{model}", torch_dtype=torch.bfloat16, local_files_only=True).to("cuda")

torch._inductor.config.conv_1x1_as_mm = True
torch._inductor.config.coordinate_descent_tuning = True
torch._inductor.config.epilogue_fusion = False
torch._inductor.config.coordinate_descent_check_all_directions = True

print("Done Loading")

pipe.set_progress_bar_config(disable=True)

pipe.transformer.to(memory_format=torch.channels_last)
pipe.transformer = torch.compile(pipe.transformer, mode="max-autotune", fullgraph=True)

pipe.vae.to(memory_format=torch.channels_last)
pipe.vae.decode = torch.compile(pipe.vae.decode, mode="max-autotune", fullgraph=True)

print("Done Compiling")


prompt = "A dinosaur in modern suit"


num_images = 4

def tensor_to_pil(tensor: torch.Tensor) -> list[Image.Image]:
    """
    Convert a batch of PyTorch tensors to a list of PIL Images.

    Parameters:
    - tensor: torch.Tensor - The tensor to convert. Assumes the tensor has a batch dimension.

    Returns:
    - list[PIL.Image.Image]: The list of tensors as PIL images.
    """
    # Convert to fp16 and move to CPU
    # ToPILImage Transform does not support bfloat16 or some other formats
    tensor = tensor.to(dtype=torch.float16, device="cpu")
    print("Done")

    transform = ToPILImage()
    images = [transform(t) for t in tensor]
    return images

for _ in range(num_images):
    print()
    start_time = time.time()
    out = pipe(
        prompt=prompt,
        guidance_scale=3.5,
        height=1024,
        width=1024,
        output_type="pt",
        num_inference_steps=28
    ).images

    print(f"Inference Time: {time.time() - start_time}")

    print("Starting to save")
    start_time = time.time()

    pil_images = tensor_to_pil(out)
    for i, img in enumerate(pil_images):
        # Save the image
        img.save(f"image{i}.png")

        print(f"Save Time: {time.time() - start_time}")

    print("Saved")
```

And here's the output

```
Inference Time: 111.78941750526428
Starting to save
Done
Save Time: 0.3608579635620117
Saved

Inference Time: 11.806470394134521
Starting to save
Done
Save Time: 0.36004066467285156
Saved

Inference Time: 3.705930471420288
Starting to save
Done
Save Time: 7.542477369308472
Saved

Inference Time: 3.5726981163024902
Starting to save
Done
Save Time: 7.612122297286987
Saved
```

The funny thing with this output is that the ratio just flips in such a way that the total time are approximately equal (11s).

**Comment by cpuhrsch** [comment]
If you're running on GPU you're using the async launch API of PyTorch, so you need to use `synchronize` to get accurate timings. See https://pytorch.org/docs/main/notes/cuda.html#asynchronous-execution

**Comment by Leommm-byte** [comment]
> > If you're running on GPU you're using the async launch API of PyTorch, so you need to use `synchronize` to get accurate timings. See https://pytorch.org/docs/main/notes/cuda.html#asynchronous-execution
> 
> Oh thank you very much. I actually tried this earlier but then I lose out on the speed 🥲. 1 image on an A100 8gb now use 10.5s on average.
> 
> From the benchmarks here, I see I'm suppose to get like 4s on average.

Oh nevermind me, I think @sayakpaul used H100 for most of those benchmark figures as I am getting similar results now. 

I also noticed that I couldn't use some of the fp8 quantization on A100 as the compute capability is low (8.0). The fp8 used here (fp8dq= fp8e4nv) works with an Nvidia GPU with ARCH/Compute capability >= 8.9. So, I found these GPUs to be well suited: H100, RTX 6000 ADA, and RTX 4090.

I also noticed `fp8dqrow ` needs a GPU with compute capability of 9.0 (I could only find H100 as at writing this comment).

Please, if there's a work around to making this work on other GPUs (like A100), do share. If there's not, I think we can update the benchmark with these details i.e. GPUs with the respective precisions they support.

Thank you and as usual, awesome work guys!

**Comment by sayakpaul** [comment]
Thanks!

> Please, if there's a work around to making this work on other GPUs (like A100), do share. If there's not, I think we can update the benchmark with these details i.e. GPUs with the respective precisions they support.

I think we already mention that FP8 related things have compute restriction. But feel free to send over a PR if you think any info is missing. 

Cc: @drisspg for FP8 as well.
